/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIClasses;

import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import java.awt.Frame;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import book_shop.DB;
import book_shop.Essencials;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Nalaranga
 */
public class CatagoryAdd extends javax.swing.JFrame {

    private static CatagoryAdd instance = null;

    
    Essencials es;
    DefaultTableModel TbModleCAT;

    public CatagoryAdd(){
        initComponents();
        es = new Essencials();
        es.setCenter(this);
        String heading[] = {"Number", "Group name", "Description"};
        es.customTBHEAD(jTable1, heading, 3, new java.awt.Color(224, 224, 224));
        TbModleCAT = (DefaultTableModel) jTable1.getModel();
        try {
            INVno(false);
            searchALL("SELECT * FROM catagories");
        } catch (Exception e) {
            e.printStackTrace();
            //new SysErrMsg(e).setVisible(true);
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfcatNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfcatName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfcatNo1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bu_cat_combo1 = new javax.swing.JButton();
        jbcat_save = new javax.swing.JButton();
        jbcat_del = new javax.swing.JButton();
        jbcat_clear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfdiscription = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));

        jPanel2.setBackground(new java.awt.Color(239, 108, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Item Category");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ic_call_received_white_18dp_1x.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ic_call_made_white_18dp_1x.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ic_close_white_18dp_1x.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Category No");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(255, 0, 0)));

        tfcatNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfcatNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));
        tfcatNo.setPreferredSize(new java.awt.Dimension(59, 28));
        tfcatNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcatNoActionPerformed(evt);
            }
        });
        tfcatNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfcatNoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Category");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(204, 204, 204)));

        tfcatName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfcatName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));
        tfcatName.setPreferredSize(new java.awt.Dimension(59, 28));
        tfcatName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcatNameActionPerformed(evt);
            }
        });
        tfcatName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfcatNameKeyReleased(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));

        jTable1.setBackground(new java.awt.Color(252, 252, 252));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(232, 232, 232));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(252, 252, 252));
        jTable1.setSelectionForeground(new java.awt.Color(255, 193, 7));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(300);
        }

        tfcatNo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfcatNo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));
        tfcatNo1.setPreferredSize(new java.awt.Dimension(59, 28));
        tfcatNo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfcatNo1KeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Category Name");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(255, 0, 0)));

        bu_cat_combo1.setBackground(new java.awt.Color(255, 255, 255));
        bu_cat_combo1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        bu_cat_combo1.setText("Search");
        bu_cat_combo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));
        bu_cat_combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_cat_combo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tfcatNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bu_cat_combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bu_cat_combo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfcatNo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jbcat_save.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jbcat_save.setForeground(new java.awt.Color(51, 51, 51));
        jbcat_save.setText("Save");
        jbcat_save.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));
        jbcat_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcat_saveActionPerformed(evt);
            }
        });
        jbcat_save.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbcat_saveKeyReleased(evt);
            }
        });

        jbcat_del.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jbcat_del.setForeground(new java.awt.Color(51, 51, 51));
        jbcat_del.setText("Delete");
        jbcat_del.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));
        jbcat_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcat_delActionPerformed(evt);
            }
        });
        jbcat_del.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbcat_delKeyReleased(evt);
            }
        });

        jbcat_clear.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jbcat_clear.setForeground(new java.awt.Color(51, 51, 51));
        jbcat_clear.setText("Clear");
        jbcat_clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));
        jbcat_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcat_clearActionPerformed(evt);
            }
        });
        jbcat_clear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbcat_clearKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Decription");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(204, 204, 204)));

        tfdiscription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfdiscription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));
        tfdiscription.setPreferredSize(new java.awt.Dimension(59, 28));
        tfdiscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdiscriptionActionPerformed(evt);
            }
        });
        tfdiscription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdiscriptionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdiscriptionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfcatName, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfcatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfdiscription, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbcat_save, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbcat_del, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbcat_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tfcatNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tfcatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tfdiscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbcat_del, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbcat_save, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbcat_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(201, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        es.setDirection(this);
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        es.moveWindow(this);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jbcat_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcat_saveActionPerformed
        try {
            JTextField tf[] = {tfcatNo, tfcatName};
            if (!es.checkEMPTY(tf)) {
                ResultSet rs = DB.search("SELECT * FROM catagories WHERE catno='" + tfcatNo.getText() + "'");
                if (rs.next()) {
                    new ConfirmMessage("Modify?", "Are you sure yo want to modify data?", false) {

                        @Override
                        void ifYes() {
                            try {
                                DB.Execute("UPDATE catagories SET catname='" + tfcatName.getText() + "',catdescription='" + tfdiscription.getText() + "' WHERE catno='" + tfcatNo.getText() + "'");
                                clearALL();
                            } catch (Exception e) {
                                e.printStackTrace();
                                //new SysErrMsg(e).setVisible(true);
                            }
                        }

                        @Override
                        void ifNo() {
                            return;
                        }
                    }.setVisible(true);
                } else {
                    DB.Execute("INSERT INTO catagories VALUES('" + tfcatNo.getText() + "','" + tfcatName.getText() + "','" + tfdiscription.getText() + "')");
                    INVno(true);
                    clearALL();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            //new SysErrMsg(e).setVisible(true);
        }
    }//GEN-LAST:event_jbcat_saveActionPerformed

    private void tfcatNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcatNoKeyTyped
        es.numsONLY(evt);
    }//GEN-LAST:event_tfcatNoKeyTyped

    private void jbcat_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcat_clearActionPerformed
        try {
            clearALL();
        } catch (Exception e) {
            e.printStackTrace();
            //new SysErrMsg(e).setVisible(true);
        }
    }//GEN-LAST:event_jbcat_clearActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            int x = jTable1.getSelectedRow();
            tfcatNo.setText(TbModleCAT.getValueAt(x, 0).toString());
            tfcatName.setText(TbModleCAT.getValueAt(x, 1).toString());
            tfdiscription.setText(TbModleCAT.getValueAt(x, 2).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbcat_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcat_delActionPerformed
        JTextField tf[] = {tfcatNo};
        if (es.checkEMPTY(tf)) {
            return;
        }
        new ConfirmMessage("Data Deletion", "Are you sure you want to delete?", false) {

            @Override
            void ifYes() {
                try {
                    DB.Execute("DELETE FROM catagories WHERE catno='" + tfcatNo.getText() + "'");
                    clearALL();
                } catch (Exception e) {
                    e.printStackTrace();
                    //new SysErrMsg(e).setVisible(true);
                }
            }

            @Override
            void ifNo() {
                return;
            }
        }.setVisible(true);
    }//GEN-LAST:event_jbcat_delActionPerformed

    private void tfdiscriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdiscriptionKeyTyped
        //es.numsONLY(evt); to check if it is not numbers
    }//GEN-LAST:event_tfdiscriptionKeyTyped

    private void tfcatNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcatNoActionPerformed
        try {
            INVno(false);
            tfcatName.grabFocus();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tfcatNoActionPerformed

    private void tfcatNo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcatNo1KeyReleased
        try {
            searchALL("SELECT * FROM catagories WHERE catname LIKE '" + tfcatNo1.getText() + "%'");
        } catch (Exception e) {
            e.printStackTrace();
            //new SysErrMsg(e).setVisible(true);
        }
    }//GEN-LAST:event_tfcatNo1KeyReleased

    private void bu_cat_combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_cat_combo1ActionPerformed
        try {
            searchALL("SELECT * FROM catagories");
            tfcatNo1.setText("");

        } catch (Exception e) {
            e.printStackTrace();
            //new SysErrMsg(e).setVisible(true);
        }
    }//GEN-LAST:event_bu_cat_combo1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        es.maximizeWin(this);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void tfcatNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcatNameKeyReleased
//        if (evt.getKeyCode() == 13) {
//            tfdiscription.grabFocus();
//        }
    }//GEN-LAST:event_tfcatNameKeyReleased

    private void tfdiscriptionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdiscriptionKeyReleased
        if (evt.getKeyCode() == 13) {
            jbcat_save.grabFocus();
        }
    }//GEN-LAST:event_tfdiscriptionKeyReleased

    private void jbcat_delKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbcat_delKeyReleased
        //Right arrow - 39
        if (evt.getKeyCode() == 39) {
            jbcat_clear.grabFocus();
        }
        //Left arrow - 37
        if (evt.getKeyCode() == 37) {
            jbcat_save.grabFocus();
        }
    }//GEN-LAST:event_jbcat_delKeyReleased

    private void jbcat_clearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbcat_clearKeyReleased
        if (evt.getKeyCode() == 37) {
            jbcat_del.grabFocus();
        }
    }//GEN-LAST:event_jbcat_clearKeyReleased

    private void tfcatNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcatNameActionPerformed
        tfdiscription.grabFocus();
    }//GEN-LAST:event_tfcatNameActionPerformed

    private void tfdiscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdiscriptionActionPerformed
        jbcat_save.grabFocus();
    }//GEN-LAST:event_tfdiscriptionActionPerformed

    private void jbcat_saveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbcat_saveKeyReleased
        //Right arrow - 39
        if (evt.getKeyCode() == 39) {
            jbcat_del.grabFocus();
        }
    }//GEN-LAST:event_jbcat_saveKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {

                    UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());

                    new CatagoryAdd().setVisible(true);

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bu_cat_combo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbcat_clear;
    private javax.swing.JButton jbcat_del;
    private javax.swing.JButton jbcat_save;
    private javax.swing.JTextField tfcatName;
    private javax.swing.JTextField tfcatNo;
    private javax.swing.JTextField tfcatNo1;
    private javax.swing.JTextField tfdiscription;
    // End of variables declaration//GEN-END:variables

    public void searchALL(String query) throws Exception {
        ResultSet rs = DB.search(query);
        TbModleCAT.setRowCount(0);
        while (rs.next()) {
            Vector v = new Vector();
            v.add(rs.getString(1));
            v.add(rs.getString(2));
            v.add(rs.getString(3));
            TbModleCAT.addRow(v);
        }

        final ArrayList ar = new ArrayList();

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            ar.add(i);
        }

        jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (Integer.parseInt(ar.get(row).toString()) % 2 == 1) {
                    c.setBackground(new java.awt.Color(253, 253, 253));
                } else {
                    c.setBackground(new Color(255, 243, 224));
                }
                return c;
            }
        });
    }

    public void clearALL() throws Exception {
        JTextField tf[] = {tfcatNo, tfcatName, tfdiscription};
        es.clearTFS(tf);
        searchALL("SELECT * FROM catagories");
        tfcatNo.grabFocus();
        INVno(false);
    }

    private void INVno(boolean isupdate) throws Exception {
        ResultSet nosrs = DB.search("SELECT no FROM nos WHERE cat=2");
        int no = 0;
        while (nosrs.next()) {
            no = nosrs.getInt(1);
        }
        if (isupdate) {
            no++;
            DB.Execute("UPDATE nos SET no='" + no + "' WHERE cat=2 ");
        }
        tfcatNo.setText("" + no);
    }
}
