/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIClasses;

import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import book_shop.CustomRenderer;
import book_shop.DB;
import book_shop.Essencials;
import book_shop.JComponentTableCellRenderer;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JTable;

/**
 *
 * @author Nalaranga
 */
public class Income extends javax.swing.JFrame {

    Essencials es;
    int CURYear;
    int CURMonth;
    int CURDate;
    String Cyear;
    Date today;
    String nowMonth;
    String nowYear;
    String nowDate;

    DefaultTableModel dtm;
    DecimalFormat df;

    public Income() {
        initComponents();
        es = new Essencials();
        es.setCenter(this);
        df = new DecimalFormat("###,###.00");

        dtm = (DefaultTableModel) jTable1.getModel();

        String vals[] = {"Number", "Date", "Time", "Amount", "Cashier"};
        es.customTBHEAD(jTable1, vals, 5, new java.awt.Color(224, 224, 224));

        today = new Date();

        Cyear = new SimpleDateFormat("yyyy").format(today);
        nowYear = Cyear;
        String monanddate = new SimpleDateFormat("MMMM-dd").format(today);
        String sr[] = monanddate.split("-");
        nowMonth = sr[0];
        nowDate = sr[1];

        JTableHeader head = jTable3.getTableHeader();
        head.setBackground(new java.awt.Color(250, 250, 250));
        head.setPreferredSize(new Dimension(100, 25));

        String tbVals[] = {"MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"};
        TableColumnModel tableColumnModel = head.getColumnModel();
        TableCellRenderer renderer = new JComponentTableCellRenderer();
        Font tbHFont = new Font("Segoe UI", Font.PLAIN, 10);
        for (int i = 0; i < 7; i++) {
            TableColumn column = tableColumnModel.getColumn(i);
            JLabel labelTBH = new JLabel(tbVals[i], JLabel.CENTER);
            labelTBH.setFont(tbHFont);
            labelTBH.setBorder(null);
            labelTBH.setForeground(Color.GRAY);
            column.setHeaderRenderer(renderer);
            column.setHeaderValue(labelTBH);
        }

        SetDates(true);
        setMonths(CURYear, CURMonth, CURDate);
        try {
            searchDATA(nowYear + "-" + getMonthInNumber(nowMonth) + "-" + nowDate);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel55 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        JlMonth = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        Jlyear = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfcat_prod = new javax.swing.JTextField();
        bu_cat_combo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bu_cat_add = new javax.swing.JButton();

        jPopupMenu1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 193, 7)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));

        jPanel2.setBackground(new java.awt.Color(239, 108, 0));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ic_call_received_white_18dp_1x.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ic_call_made_white_18dp_1x.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ic_close_white_18dp_1x.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 243, 224));
        jLabel4.setText("Income");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 442, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 235, 235)));
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTable3.setBackground(new java.awt.Color(252, 252, 252));
        jTable3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTable3.setForeground(new java.awt.Color(102, 102, 102));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "2", "3", "4", "5", "6", null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable3.setGridColor(new java.awt.Color(220, 220, 220));
        jTable3.setRowHeight(52);
        jTable3.setSelectionBackground(new java.awt.Color(250, 250, 250));
        jTable3.setSelectionForeground(new java.awt.Color(102, 102, 102));
        jTable3.setShowHorizontalLines(false);
        jTable3.setShowVerticalLines(false);
        jTable3.getTableHeader().setResizingAllowed(false);
        jTable3.getTableHeader().setReorderingAllowed(false);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable3);

        jPanel55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 235, 235)));

        jPanel56.setBackground(new java.awt.Color(252, 252, 252));

        JlMonth.setBackground(new java.awt.Color(252, 252, 252));
        JlMonth.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        JlMonth.setForeground(new java.awt.Color(102, 102, 102));
        JlMonth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlMonth.setText("September");
        JlMonth.setToolTipText("");
        JlMonth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlMonth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlMonthMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel56Layout = new javax.swing.GroupLayout(jPanel56);
        jPanel56.setLayout(jPanel56Layout);
        jPanel56Layout.setHorizontalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel56Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JlMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel56Layout.setVerticalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JlMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ARROWL.png"))); // NOI18N
        jLabel52.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel52MouseClicked(evt);
            }
        });

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ARROWR.png"))); // NOI18N
        jLabel51.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel51MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel55Layout = new javax.swing.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 235, 235)));
        jPanel54.setPreferredSize(new java.awt.Dimension(209, 31));

        jPanel58.setBackground(new java.awt.Color(252, 252, 252));
        jPanel58.setPreferredSize(new java.awt.Dimension(178, 29));

        Jlyear.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        Jlyear.setForeground(new java.awt.Color(102, 102, 102));
        Jlyear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlyear.setText("2014");
        Jlyear.setToolTipText("");
        Jlyear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jlyear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlyearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel58Layout = new javax.swing.GroupLayout(jPanel58);
        jPanel58.setLayout(jPanel58Layout);
        jPanel58Layout.setHorizontalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel58Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jlyear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel58Layout.setVerticalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jlyear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ARROWL.png"))); // NOI18N
        jLabel49.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel49MouseClicked(evt);
            }
        });

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ARROWR.png"))); // NOI18N
        jLabel48.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel48MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel54Layout = new javax.swing.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel54Layout.createSequentialGroup()
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel58, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel58, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
            .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 50)); // NOI18N
        jLabel1.setText("Rs. 79,000.00");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(255, 193, 7)));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(224, 224, 224)));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(235, 235, 235));
        jTable1.setRowHeight(22);
        jTable1.setSelectionBackground(new java.awt.Color(252, 252, 252));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(jTable1);

        tfcat_prod.setBackground(new java.awt.Color(253, 253, 253));
        tfcat_prod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfcat_prod.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(224, 224, 224)));
        tfcat_prod.setPreferredSize(new java.awt.Dimension(59, 28));
        tfcat_prod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfcat_prodKeyReleased(evt);
            }
        });

        bu_cat_combo.setBackground(new java.awt.Color(253, 253, 253));
        bu_cat_combo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow-204-16.png"))); // NOI18N
        bu_cat_combo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(224, 224, 224)));
        bu_cat_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_cat_comboActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        bu_cat_add.setBackground(new java.awt.Color(253, 253, 253));
        bu_cat_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add-file-16.png"))); // NOI18N
        bu_cat_add.setToolTipText("");
        bu_cat_add.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(224, 224, 224)));
        bu_cat_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_cat_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                            .addComponent(jPanel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel54, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tfcat_prod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(bu_cat_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(bu_cat_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bu_cat_combo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfcat_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bu_cat_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        es.maximizeWin(this);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        es.setDirection(this);
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        es.moveWindow(this);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        try {
            String dt = jTable3.getModel().getValueAt(jTable3.getSelectedRow(), jTable3.getSelectedColumn()).toString();
            if (Integer.parseInt(dt) < 10) {
                dt = "0" + dt;
            }
            searchDATA(Jlyear.getText() + "-" + getMonthInNumber(JlMonth.getText()) + "-" + dt);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable3MouseClicked

    private void jLabel52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel52MouseClicked
        updateCurrentDate(3);
    }//GEN-LAST:event_jLabel52MouseClicked

    private void jLabel51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MouseClicked
        updateCurrentDate(4);
    }//GEN-LAST:event_jLabel51MouseClicked

    private void jLabel49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MouseClicked
        updateCurrentDate(1);
    }//GEN-LAST:event_jLabel49MouseClicked

    private void jLabel48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseClicked
        updateCurrentDate(2);
    }//GEN-LAST:event_jLabel48MouseClicked

    private void JlMonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlMonthMouseClicked
        try {
            searchDATA(Jlyear.getText() + "-" + getMonthInNumber(JlMonth.getText()));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_JlMonthMouseClicked

    private void JlyearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlyearMouseClicked
        try {
            searchDATA(Jlyear.getText());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_JlyearMouseClicked

    private void tfcat_prodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcat_prodKeyReleased
        try {
            ResultSet rscat = DB.search("SELECT username FROM user WHERE username LIKE '" + tfcat_prod.getText() + "%'");
            Vector v = new Vector();
            while (rscat.next()) {
                v.add(rscat.getString(1));
            }
            es.JSuggestionField(evt, v, tfcat_prod, jPanel3, jPopupMenu1, tfcat_prod, bu_cat_combo);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tfcat_prodKeyReleased

    private void bu_cat_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_cat_comboActionPerformed
        try {
            ResultSet rscat = DB.search("SELECT username FROM user");
            Vector v = new Vector();
            while (rscat.next()) {
                v.add(rscat.getString(1));
            }
            es.JSuggestionField(null, v, tfcat_prod, jPanel3, jPopupMenu1, tfcat_prod, bu_cat_combo);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bu_cat_comboActionPerformed

    private void bu_cat_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_cat_addActionPerformed
        tfcat_prod.setText("");
    }//GEN-LAST:event_bu_cat_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
                    new Income().setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlMonth;
    private javax.swing.JLabel Jlyear;
    private javax.swing.JButton bu_cat_add;
    private javax.swing.JButton bu_cat_combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField tfcat_prod;
    // End of variables declaration//GEN-END:variables

    private void setMonths(int year, int month, int day) {
        Calendar cal = new GregorianCalendar();
        Calendar cal2 = new GregorianCalendar();
        cal2.setFirstDayOfWeek(Calendar.MONDAY);
        cal.setFirstDayOfWeek(Calendar.MONDAY);

        if (year != 0) {
            cal.set(Calendar.YEAR, year);
        }
        if (month != 0) {
            cal.set(Calendar.MONTH, month - 1);
        }
        if (day != 0) {
            cal.set(Calendar.DATE, day);
        }
        int CMONTH = cal.get(GregorianCalendar.MONTH);
        int get1 = cal.getActualMaximum(GregorianCalendar.DAY_OF_MONTH);
        DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            for (int j = 0; j < dtm.getColumnCount(); j++) {
                dtm.setValueAt("", i, j);
            }
        }
        TableCellRenderer cellPrevious = null;
        for (int i = 1; i <= get1; i++) {
            cal2.set(cal.get(Calendar.YEAR), CMONTH, i);
            String Day = new SimpleDateFormat("u").format(cal2.getTime());
            int Dy = Integer.parseInt(Day) - 1;
            int initDay = cal2.get(Calendar.WEEK_OF_MONTH) - 1;

//            String dtno = "" + i;
//            if (i < 10) {
//                dtno = "0" + i;
//            }
            dtm.setValueAt("" + i, initDay, Dy);

            if (JlMonth.getText().equals(nowMonth) & Jlyear.getText().equals(nowYear)) {
                cellPrevious = jTable3.getColumnModel().getColumn(0).getCellRenderer();
                jTable3.getColumnModel().getColumn(Dy).setCellRenderer(new CustomRenderer(nowDate));
            } else {
                jTable3.getColumnModel().getColumn(Dy).setCellRenderer(cellPrevious);
            }
        }
        final DefaultTableCellRenderer rightRenderer = (DefaultTableCellRenderer) jTable3.getCellRenderer(0, 0);
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < 7; i++) {
            jTable3.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
        }
    }

    private String SetDates(boolean UPNO) {
        String Todate = null;
        Calendar calendar = new GregorianCalendar();
        if (UPNO) {
            CURYear = calendar.get(Calendar.YEAR);
            CURMonth = calendar.get(Calendar.MONTH) + 1;
            CURDate = calendar.get(Calendar.DATE);
        }
        Todate = CURYear + "-" + getMonthInName(CURMonth) + "-" + CURDate;
        Jlyear.setText("" + CURYear);
        JlMonth.setText(getMonthInName(CURMonth));
        return Todate;
    }

    private void updateCurrentDate(int status) {
        CURYear = Integer.parseInt(Jlyear.getText());
        CURMonth = Integer.parseInt(getMonthInNumber(JlMonth.getText()));

        if (status == 1) {
            int yy = CURYear - 1;
            CURYear = yy;
            Jlyear.setText("" + CURYear);
        } else if (status == 2) {
            int yy = CURYear + 1;
            CURYear = yy;
            Jlyear.setText("" + CURYear);
        } else if (status == 3) {
            if (CURMonth == 1) {
                CURMonth = 13;
            }
            int yy = CURMonth - 1;
            CURMonth = yy;
            JlMonth.setText(getMonthInName(CURMonth));
        } else if (status == 4) {
            if (CURMonth == 12) {
                CURMonth = 0;
            }
            int yy = CURMonth + 1;
            CURMonth = yy;
            JlMonth.setText(getMonthInName(CURMonth));
        }

        setMonths(CURYear, CURMonth, CURDate);
    }

    private String getMonthInNumber(String month) {
        String mon = "";
        switch (month) {
            case "January":
                mon = "01";
                break;
            case "February":
                mon = "02";
                break;
            case "March":
                mon = "03";
                break;
            case "April":
                mon = "04";
                break;
            case "May":
                mon = "05";
                break;
            case "June":
                mon = "06";
                break;
            case "July":
                mon = "07";
                break;
            case "August":
                mon = "08";
                break;
            case "September":
                mon = "09";
                break;
            case "October":
                mon = "10";
                break;
            case "November":
                mon = "11";
                break;
            case "December":
                mon = "12";
                break;

        }
        return mon;
    }

    private String getMonthInName(int month) {
        String mon = null;
        switch (month) {
            case 1:
                mon = "January";
                break;
            case 2:
                mon = "February";
                break;
            case 3:
                mon = "March";
                break;
            case 4:
                mon = "April";
                break;
            case 5:
                mon = "May";
                break;
            case 6:
                mon = "June";
                break;
            case 7:
                mon = "July";
                break;
            case 8:
                mon = "August";
                break;
            case 9:
                mon = "September";
                break;
            case 10:
                mon = "October";
                break;
            case 11:
                mon = "November";
                break;
            case 12:
                mon = "December";
                break;

        }
        return mon;

    }

    private void searchDATA(String date) throws Exception {
        jLabel3.setText("You Selected " + date);
        ResultSet rs = DB.search("SELECT invno,date,time,amount,cashier FROM payments WHERE date LIKE'" + date + "%' AND cashier LIKE '" + tfcat_prod.getText() + "%'");
        dtm.setRowCount(0);
        while (rs.next()) {
            Vector v = new Vector();
            v.add(rs.getString(1));
            v.add(rs.getString(2));
            v.add(rs.getString(3));
            v.add(df.format(rs.getDouble(4)));
            v.add(rs.getString(5));
            dtm.addRow(v);
        }
        double tota = 0;
        try {
            ResultSet rs2 = DB.search("SELECT SUM(amount) FROM payments WHERE date LIKE '" + date + "%' AND cashier LIKE '" + tfcat_prod.getText() + "%'");
            while (rs2.next()) {
                tota = rs2.getDouble(1);
            }
            jLabel1.setText("Rs. " + df.format(tota));
            setCOLORSTB(jTable1);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setCOLORSTB(JTable table) {

        final ArrayList ar = new ArrayList();

        for (int i = 0; i < table.getRowCount(); i++) {
            ar.add(i);
        }

        table.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (Integer.parseInt(ar.get(row).toString()) % 2 == 1) {
                    c.setBackground(new java.awt.Color(253, 253, 253));
                } else {
                    c.setBackground(new Color(255, 243, 224));
                }
                return c;
            }
        });
    }

}
